### ISSUE TITLE
Spoiled Ballot Check Description Needs Expansion

### ISSUE THREAD

**Issue by nickboucher** [microsoft/electionguard-verifier#3]
In *README.md*, the description of the checks sufficient to prove election correctness states the following for spoiled ballots:
```markdown
- For each spoiled ballot, we check:
  ...
  - An assortment of other validity and well-formedness checks [TODO: expand on this]
```
This description needs expansion, as the `TODO` implies, in order to be useful. While the Rust implementation in `src/` can be consulted, having all checks listed directly on the Readme is helpful to independent developers implementing their own verifiers.

**Comment by echumley-msft** [comment]
Hi, thanks for raising this issue - we've recently transitioned the primary ElectionGuard reference implementation to the [ElectionGuard-Python](https://github.com/microsoft/electionguard-python) repository. The team believes this issue has been resolved or mitigated there, so closing this issue for now as this repository will no longer be actively maintained. Please feel free to check and leave comments in the latest [repo](https://github.com/microsoft/electionguard-python).
